import React, { useState, useEffect } from 'react';
import { getEvents } from '../../../utils/adminDashboardAPI';
import './Modal.css';

const AddRegistrationModal = ({ onClose, onAdd }) => {
  const [formData, setFormData] = useState({
    fullName: '',
    emailAddress: '',
    contactNumber: '',
    collegeName: '',
    year: '',
    eventName: '',
    numberOfParticipants: '1',
    participants: [],
    teamName: '',
    fifaUsername: '',
    teamOvr: '',
    deviceModel: '',
    gameUsername: '',
    playerRating: '',
    gamingPlatform: '',
    paymentMode: 'online',
    transactionId: '',
    paymentStatus: 'pending',
    registrationStatus: 'confirmed',
  });
  const [events, setEvents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [validationError, setValidationError] = useState('');

  // Event participant configurations
  const eventParticipantConfig = {
    'Technomania': { min: 1, max: 4, isTeam: false },
    'Ro-Navigator': { min: 2, max: 5, isTeam: true },
    'Ro-Combat': { min: 2, max: 5, isTeam: true },
    'Ro-Soccer': { min: 2, max: 5, isTeam: true },
    'Ro-Terrance': { min: 2, max: 5, isTeam: true },
    'Ro-Sumo': { min: 2, max: 5, isTeam: true },
    'Tech Hunt': { min: 3, max: 5, isTeam: true },
    'Omegatrix': { min: 1, max: 1, isTeam: false },
    'Creative Canvas': { min: 1, max: 2, isTeam: true },
    'Passion With Reels': { min: 2, max: 8, isTeam: true },
    'Khet': { min: 1, max: 1, isTeam: false },
    'Forza Horizon': { min: 1, max: 1, isTeam: false },
    'FIFA Mobile': { min: 1, max: 1, isTeam: false },
  };

  const getEventConfig = () => {
    return eventParticipantConfig[formData.eventName] || { min: 1, max: 1, isTeam: false };
  };

  const isFifaMobileEvent = /fifa|fc mobile/i.test(formData.eventName || '');

  useEffect(() => {
    fetchEvents();
  }, []);

  const fetchEvents = async () => {
    try {
      const result = await getEvents();
      setEvents(result.events || []);
    } catch (err) {
      console.error('Error fetching events:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => {
      const updated = { ...prev, [name]: value };
      
      // Reset participants when event changes
      if (name === 'eventName') {
        const config = eventParticipantConfig[value] || { min: 1, max: 1, isTeam: false };
        updated.numberOfParticipants = String(config.min);
        updated.participants = [];
        updated.teamName = '';
      }
      
      // Update participants array when number changes
      if (name === 'numberOfParticipants') {
        const count = parseInt(value) || 1;
        updated.participants = Array.from({ length: count }, (_, i) => 
          updated.participants[i] || { name: '', email: '', contact: '', college: '', year: '' }
        );
      }
      
      return updated;
    });
    setValidationError('');
  };

  const handleParticipantChange = (index, field, value) => {
    setFormData(prev => {
      const participants = [...prev.participants];
      participants[index] = { ...participants[index], [field]: value };
      return { ...prev, participants };
    });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    
    // Validate transaction ID for online payments
    if (formData.paymentMode === 'online' && !formData.transactionId.trim()) {
      setValidationError('Transaction ID is required for online payments');
      return;
    }
    
    const config = getEventConfig();
    
    // Validate team name for team events
    if (config.isTeam && !formData.teamName.trim()) {
      setValidationError('Team name is required for team events');
      return;
    }
    
    // Pass the form data to parent - registration number will be generated by backend
    const newRegistration = {
      ...formData,
      submittedAt: new Date().toISOString(),
      source: 'admin',
    };

    onAdd(newRegistration);
    onClose();
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content large-modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <h2>Add New Registration</h2>
          <button className="modal-close" onClick={onClose}>✕</button>
        </div>

        <form onSubmit={handleSubmit}>
          <div className="modal-body">
            {loading ? (
              <div className="modal-inline-loading" aria-busy="true">
                <span className="loader-spinner" aria-hidden="true" />
                <p>Loading events…</p>
              </div>
            ) : (
              <>
            <div className="form-section">
              <h3>Participant Information</h3>
              
              {validationError && (
                <div className="info-box error" style={{ marginBottom: '15px', backgroundColor: '#fee', color: '#c00', border: '1px solid #fcc' }}>
                  <p>❌ {validationError}</p>
                </div>
              )}
              
              <div className="form-grid">
                <div className="form-field">
                  <label>Event *</label>
                  <select
                    name="eventName"
                    value={formData.eventName}
                    onChange={handleChange}
                    required
                  >
                    <option value="">Select Event</option>
                    {events.map(event => (
                      <option key={event.name} value={event.name}>{event.name}</option>
                    ))}
                  </select>
                </div>
                
                {formData.eventName && (
                  <>
                    {getEventConfig().isTeam && (
                      <div className="form-field">
                        <label>Team Name *</label>
                        <input
                          type="text"
                          name="teamName"
                          value={formData.teamName}
                          onChange={handleChange}
                          placeholder="Enter team name"
                          required
                        />
                      </div>
                    )}
                    
                    <div className="form-field">
                      <label>Number of Participants *</label>
                      <select
                        name="numberOfParticipants"
                        value={formData.numberOfParticipants}
                        onChange={handleChange}
                        required
                      >
                        {Array.from(
                          { length: getEventConfig().max - getEventConfig().min + 1 },
                          (_, i) => getEventConfig().min + i
                        ).map(num => (
                          <option key={num} value={num}>{num} Participant{num > 1 ? 's' : ''}</option>
                        ))}
                      </select>
                      <small style={{ color: '#666', fontSize: '12px' }}>
                        {getEventConfig().min === getEventConfig().max 
                          ? `Solo event (${getEventConfig().min} participant)`
                          : `Team event (${getEventConfig().min}-${getEventConfig().max} participants)`}
                      </small>
                    </div>
                  </>
                )}
              </div>
              
              {formData.eventName && parseInt(formData.numberOfParticipants) > 0 && (
                <div style={{ marginTop: '20px' }}>
                  <h4 style={{ marginBottom: '15px', color: '#0f766e' }}>Participant Details</h4>
                  {Array.from({ length: parseInt(formData.numberOfParticipants) }).map((_, index) => (
                    <div key={index} style={{ 
                      padding: '15px', 
                      backgroundColor: '#f9fafb', 
                      borderRadius: '8px', 
                      marginBottom: '15px',
                      border: '1px solid #e5e7eb'
                    }}>
                      <h5 style={{ marginBottom: '10px', color: '#374151' }}>Participant {index + 1}</h5>
                      <div className="form-grid">
                        <div className="form-field">
                          <label>Full Name *</label>
                          <input
                            type="text"
                            value={formData.participants[index]?.name || ''}
                            onChange={(e) => handleParticipantChange(index, 'name', e.target.value)}
                            placeholder="Enter full name"
                            required
                          />
                        </div>
                        <div className="form-field">
                          <label>Email *</label>
                          <input
                            type="email"
                            value={formData.participants[index]?.email || ''}
                            onChange={(e) => handleParticipantChange(index, 'email', e.target.value)}
                            placeholder="email@example.com"
                            required
                          />
                        </div>
                        <div className="form-field">
                          <label>Contact *</label>
                          <input
                            type="tel"
                            value={formData.participants[index]?.contact || ''}
                            onChange={(e) => handleParticipantChange(index, 'contact', e.target.value)}
                            placeholder="10-digit mobile"
                            pattern="[0-9]{10}"
                            required
                          />
                        </div>
                        <div className="form-field">
                          <label>College *</label>
                          <input
                            type="text"
                            value={formData.participants[index]?.college || ''}
                            onChange={(e) => handleParticipantChange(index, 'college', e.target.value)}
                            placeholder="College name"
                            required
                          />
                        </div>
                        <div className="form-field">
                          <label>Year *</label>
                          <select
                            value={formData.participants[index]?.year || ''}
                            onChange={(e) => handleParticipantChange(index, 'year', e.target.value)}
                            required
                          >
                            <option value="">Select Year</option>
                            <option value="1st Year">1st Year</option>
                            <option value="2nd Year">2nd Year</option>
                            <option value="3rd Year">3rd Year</option>
                            <option value="4th Year">4th Year</option>
                          </select>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>

            <div className="form-section">
              <h3>Payment Details</h3>
              <div className="form-grid">
                <div className="form-field">
                  <label>Payment Mode *</label>
                  <select
                    name="paymentMode"
                    value={formData.paymentMode}
                    onChange={handleChange}
                    required
                  >
                    <option value="online">Online</option>
                    <option value="offline">Offline</option>
                  </select>
                </div>
                <div className="form-field">
                  <label>Transaction ID {formData.paymentMode === 'online' ? '*' : ''}</label>
                  <input
                    type="text"
                    name="transactionId"
                    value={formData.transactionId}
                    onChange={handleChange}
                    placeholder={formData.paymentMode === 'online' ? 'Enter transaction ID (required)' : 'Enter transaction ID (optional)'}
                    required={formData.paymentMode === 'online'}
                  />
                  {formData.paymentMode === 'online' && (
                    <small style={{ color: '#dc2626', fontSize: '12px' }}>
                      Required for online payments
                    </small>
                  )}
                </div>
                <div className="form-field">
                  <label>Payment Status *</label>
                  <select
                    name="paymentStatus"
                    value={formData.paymentStatus}
                    onChange={handleChange}
                    required
                  >
                    <option value="pending">Pending</option>
                    <option value="verified">Verified</option>
                    <option value="failed">Failed</option>
                  </select>
                </div>
                <div className="form-field">
                  <label>Registration Status *</label>
                  <select
                    name="registrationStatus"
                    value={formData.registrationStatus}
                    onChange={handleChange}
                    required
                  >
                    <option value="confirmed">Confirmed</option>
                    <option value="pending">Pending</option>
                    <option value="cancelled">Cancelled</option>
                  </select>
                </div>
              </div>
            </div>

            {isFifaMobileEvent && (
              <div className="form-section">
                <h3>Game Details</h3>
                <div className="form-grid">
                  <div className="form-field">
                    <label>FIFA Username</label>
                    <input
                      type="text"
                      name="fifaUsername"
                      value={formData.fifaUsername}
                      onChange={handleChange}
                      placeholder="Enter FIFA username"
                    />
                  </div>
                  <div className="form-field">
                    <label>Team OVR</label>
                    <input
                      type="text"
                      name="teamOvr"
                      value={formData.teamOvr}
                      onChange={handleChange}
                      placeholder="Enter team OVR"
                    />
                  </div>
                  <div className="form-field">
                    <label>Device Model</label>
                    <input
                      type="text"
                      name="deviceModel"
                      value={formData.deviceModel}
                      onChange={handleChange}
                      placeholder="Enter device model"
                    />
                  </div>
                  <div className="form-field">
                    <label>Game Username</label>
                    <input
                      type="text"
                      name="gameUsername"
                      value={formData.gameUsername}
                      onChange={handleChange}
                      placeholder="Enter game username"
                    />
                  </div>
                  <div className="form-field">
                    <label>Player Rating</label>
                    <input
                      type="text"
                      name="playerRating"
                      value={formData.playerRating}
                      onChange={handleChange}
                      placeholder="Enter player rating"
                    />
                  </div>
                  <div className="form-field">
                    <label>Gaming Platform</label>
                    <input
                      type="text"
                      name="gamingPlatform"
                      value={formData.gamingPlatform}
                      onChange={handleChange}
                      placeholder="Enter gaming platform"
                    />
                  </div>
                </div>
              </div>
            )}

            <div className="info-box success">
              <p>✅ Registration number will be auto-generated upon submission</p>
            </div>
              </>
            )}
          </div>

          <div className="modal-footer">
            <button type="button" className="btn-secondary" onClick={onClose}>Cancel</button>
            <button type="submit" className="btn-primary" disabled={loading}>Add Registration</button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default AddRegistrationModal;
